services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGRST_DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=anon
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgrest
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  pgdata:
