services:
  # PostgreSQL service
  postgres:
    image: postgres:15.3-alpine
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw # Use data/postgres directory as volume
    ports:
      - 5432:5432

  # Web app service
  web_app:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
